config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :lists
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  # spécifie que paperclip aura a géré :picture
  # que le fichier original sera redimensionné en 1920x1800
  # et que thumb sere redimensionné en 200x200
  # si le fichier ne devait pas être présent c'est
  # le fichiers missing.png qui sera affiché dans les 2 dimensions

  has_attached_file :picture, styles: { original: "1920x1800>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"

  # on s'assure que le fichier envoyé sera de type 'image'
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  # On vérifie que le fichier aura l'extension 'png', 'jpg', 'jpeg'
  validates_attachment_file_name :picture, matches: [/png\Z/, /jpe?g\Z/, /pdf\Z/]

  # On vérifie que l'image envoyé ne fasse pas plus d'un 1M
  validates_with AttachmentSizeValidator, attributes: :picture, less_than: 1.megabytes

  # on vérifie que le champ est bien rempli
  validates :picture, presence: true

  belongs_to :user
  belongs_to :vehicle
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
      @lists = if current_user.admin?
                List.all
              else
                List.where(user_id: current_user)
              end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:date, :reason, :nb_km, :taxe_coef, :ride, :start, :arrival, :picture, :vehicle_id, :user_id)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
  def get_ride(number)
  case number
  when 1 then 'Way'
  when 2 then 'Back'
  when 3 then 'Two-Way'
  end
end
end

app/views/lists/_form.html.erb
<%= form_for @list, html: { multipart: true } do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :nb_km %><br>
    <%= f.number_field :nb_km %>
  </div>
  <div class="field">
    <%= f.label :taxe_coef %><br>
    <%= f.number_field :taxe_coef %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :vehicle_id %><br>
    <%= f.number_field :vehicle_id %>
  </div>
  <div class="field">
    <%= f.label :ride %><br>
    <%= f.select :ride, options_for_select({"way" => "1", "back" => "2", "two-way" => "3"}) %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.text_field :start %>
  </div>
  <div class="field">
    <%= f.label :arrival %><br>
    <%= f.text_field :arrival %>
  </div>
  <div class="field">
    <%= f.label :upload %>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lists</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Reason</th>
      <th>Nb km</th>
      <th>Taxe coef</th>
      <th>User</th>
      <th>Vehicle</th>
      <th>Ride</th>
      <th>Start</th>
      <th>Arrival</th>
      <th>Attachment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.date %></td>
        <td><%= list.reason %></td>
        <td><%= list.nb_km %></td>
        <td><%= list.taxe_coef %></td>
        <td><%= list.user_id %></td>
        <td><%= list.vehicle_id %></td>
        <td><%= get_ride(list.ride) %></td>
        <td><%= list.start %></td>
        <td><%= list.arrival %></td>
        <td><%= image_tag list.picture.url(:thumb) %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New List', new_list_path %>
<br>
<%= link_to 'Admin vehicle', vehicles_path, :class => 'navbar-link' %>
<br>



<br>

<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @list.date %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @list.reason %>
</p>

<p>
  <strong>Nb km:</strong>
  <%= @list.nb_km %>
</p>

<p>
  <strong>Taxe coef:</strong>
  <%= @list.taxe_coef %>
</p>

<p>
  <strong>User:</strong>
  <%= @list.user_id %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @list.vehicle_id %>
</p>

<p>
  <strong>Ride:</strong>
  <%= get_ride(@list.ride) %>
</p>

<p>
  <strong>Start:</strong>
  <%= @list.start %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @list.arrival %>
</p>

<p>
  <strong>Attachement:</strong>
  <%= image_tag(@list.picture.url(:thumb)) %>
</p>


<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>