config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :lists
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  root 'lists#index'

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :user
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:brand, :model, :power, :vehicle_type, :user_id)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br>
    <%= f.select :brand, options_for_select({"Alfa Romeo" => "Alfa Romeo",
       "Aston Martin" => "Aston Martin",
       "Audi" => "Audi",
       "BMW" => "BMW",
       "Chevrolet" => "Chevrolet",
       "Chrysler" => "Chrysler",
       "Ferrari" => "Ferrari",
       "FIAT" => "FIAT",
       "Ford" => "Ford",
       "Honda" => "Honda",
       "Hyundai" => "Hyundai",
       "Jaguar" => "Jaguar",
       "Jeep" => "Jeep",
       "Kia" => "Kia",
       "Lamborghini" => "Lamborghini",
       "Lancia" => "Lancia",
       "Land Rover" => "Land Rover",
       "Mazda" => "Mazda",
       "Mercedes-Benz" => "Mercedes-Benz",
       "MINI" => "MINI",
       "Mitsubishi" => "Mitsubishi",
       "Nissan" => "Nissan",
       "Peugeot" => "Peugeot",
       "Porsche" => "Porsche",
       "Renault" => "Renault",
       "Saab" => "Saab",
       "smart" => "smart",
       "Subaru" => "Subaru",
       "Suzuki" => "Suzuki",
       "Tesla" => "Tesla",
       "Toyota" => "Toyota",
       "Volkswagen" => "Volkswagen",
       "Volvo" => "Volvo"}) %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :power %><br>
    <%= f.number_field :power %>
  </div>
  <div class="field">
    <%= f.label :vehicle_type %><br>
    <%= f.select :vehicle_type, options_for_select({"car" => "car", "bike <50" => "bike <50", "bike >50" => "bike >50"}) %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Power</th>
      <th>Type</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.brand %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.power %></td>
        <td><%= vehicle.vehicle_type %></td>
        <td><%= vehicle.user_id %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>
<br>
<%= link_to 'Back', lists_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @vehicle.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Power:</strong>
  <%= @vehicle.power %>
</p>

<p>
  <strong>Type:</strong>
  <%= @vehicle.vehicle_type %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @vehicle.user_id %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>